name: Deploy to Production

on: 
  pull_request: 
    branches:
      - main
    
jobs:
  deploy:
    
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4
    
      - name: Validar Branchs
        run: |
          if [[ ! "${{ github.event.pull_request.head.ref }}" == main* ]]; then            
            echo "❌ ERRO: A branch de origem não começa com 'main'. Merge bloqueado!"            
            exit 1
          fi
          echo "Branch de origem é main"

      - name: Executar Logs e Deploy
        run: |
          echo "Branch de origem: ${{ github.event.pull_request.head.ref }}"
          echo "Branch de destino: ${{ github.event.pull_request.base.ref }}"
          echo "Fazendo deploy..."
