name: Deploy to Preproduction Backend

on: 
  pull_request: 
    branches:
      - main-Back
    
jobs:
  deploy:
    
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4
    
      - name: Validar Branch de origem
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          if [[ "$HEAD_REF" != main* ]]; then
            echo "❌ ERRO: A branch de origem ('$HEAD_REF') não começa com 'main'. Merge bloqueado!"
            exit 1
          fi
          echo "✅ Branch de origem é '$HEAD_REF' — liberado."
          
            - name: Executar Deploy
              run: |
                echo "Fazendo deploy..."
