name: Deploy to Preproduction Frontend

on: 
  pull_request: 
    branches:
      - main-Front
    
jobs:
  deploy:
    
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Codigo
        uses: actions/checkout@v4
    

      - name: Validar Branchs
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "dev-Front" ]; then
            echo "❌ ERRO: A branch de origem não é 'dev-Front'. Merge bloqueado!"
            exit 1
          fi
          echo "Branch de origem é dev-Front"
    
      - name: Executar Logs e Deploy
        run: |
          echo "Branch de origem: ${{ github.event.pull_request.head.ref }}"
          echo "Branch de destino: ${{ github.event.pull_request.base.ref }}"
          echo "Fazendo deploy..."
